<script lang="ts">
	import { Button } from "../ui/button";


    export let isLoading : boolean = false;
    export let styles : string = "";
    export let type : "button" | "submit" = "submit";
    export let action : string | undefined = undefined;
</script>
<Button class="{styles}" {type} disabled={isLoading} formaction={action}>
    <slot />
    {#if isLoading}
        <svg class="max-w-full" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="50" height="50" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-linecap="round" fill="none" stroke-dasharray="50.26548245743669 50.26548245743669" stroke="#ffffff" stroke-width="8" r="32" cy="50" cx="50">
            <animateTransform values="0 50 50;360 50 50" keyTimes="0;1" dur="1s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
        </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
    {/if}
</Button>